# Generated by Django 5.0.6 on 2024-06-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_delete_menu_remove_menuitem_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='reservation_date',
        ),
    ]
